let suggestions = [
    "Cookbook",
    "Java Assignment 1: Console Applications",
    "Java Assignment 2: Currency Converter",
    "Java Assignment 2.5: Change Calculator",
    "Java Assignment 3: Loop Practice",
    "Java Assignment 4: Arrays: Family Budget",
    "Java Assignment 4: Arrays: RackO",
    "Java Assignment 5: Swing Practice",
    "Java Assignment 6: Final Project: Tic Tac Toe",
    "Unit 1: Intro to Computers",
    "Unit 2: Data and Variables",
    "Unit 3: Control Flow",
    "Unit 4: Looping and Random",
    "Unit 5: Methods/Functions",
    "Netbeans Setup",
    "GUI Survival Guide",
    "Java Bonus: Coin Flip Problem",
    "Java Bonus: Fox Goose Grain",
    "Summer Assignment",
    "APCS Assignment 1: Computer Components",
    "APCS Assignment 2: Operations Calculator",
    "APCS Assignment 3: Stairway To Heaven",
    "APCS Assignment 4: Tidbit Computer Store",
    "APCS Assignment 5: Input Verifiers",
    "APCS Assignment 6: Group Presentations",
    "APCS Assignment 7: Object Oriented Programming",
    "APCS Assignment 8: Additional Class Features",
    "APCS Assignment 9: String Methods",
    "APCS Assignment 10: 2-Dimensional Arrays",
    "APCS Assignment 11: List Management",
    "APCS Assignment 12: Object Oriented Polymorphism",
    "APCS Assignment 13: Ethical Software",
    "APCS Assignment 14: Stacks",
    "APCS Assignment 15: Method Recursion",
    "APCS Assignment 16: Intel Pentium Bug",
    "APCS Assignment 17: Searching and Sorting",
    "APCS Assignment 18: Hangman",
    "Final Project: Connect 4",
    "Unit 1: Systems",
    "Unit 2: Math Operations",
    "Unit 3: Primitives/Objects",
    "Unit 4: Object Oriented",
    "Unit 5: Strings",
    "Unit 6: Arrays & ArrayLists",
    "Unit 7: File IO",
    "Unit 8: Inheritance & Polymorphism",
    "Unit 9: Recursion",
    "Unit 10: Stacks",
    "Unit 11: Ethical Issues",
    "Unit 12: Searching and Sorting",
    "PNZ Game",
    "Blackjack Game",
    "Yahtzee Game",
    "Hotel System",
    "Risk Game",
    "Battleship",
    "W3Schools",
    "SoloLearn",
    "Programiz",
    "Code Academy"
];
